name: glare
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2 

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_crashlytics: ^3.0.0

  dropdown_button2: ^2.3.9
  
  smooth_page_indicator: ^1.2.0

  firebase_core: ^2.27.2

  user_repository:
   path: packages/user_repository
  
  event_repository:
    path: packages/event_repo

  venue_repository:
    path: packages/venue_repo

  venue_favorite_repository:
    path: packages/venue_fav_repo

  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  cupertino_icons: ^1.0.6
  firebase_database: ^10.4.11
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.18.0
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  rxdart: ^0.27.7
  url_launcher: ^6.2.5
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.10
  intl: ^0.17.0
  shared_preferences: ^2.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

  flutter_native_splash: ^2.2.17

flutter_native_splash:
  color: "#000000"  # Background color of the splash screen
  image: assets/icons/glare-8.png  # Path to your splash image
  android: true


flutter:
  assets:
    - assets/images/
    - assets/Style_img/
    - assets/icons/
    - assets/icons/Navbar/
    - assets/icons/Profile_screen/
  uses-material-design: true
