name: glare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.25.4

  user_repository:
   path: packages/user_repository
  
  event_repository:
    path: packages/event_repo

  venue_repository:
    path: packages/venue_repo

  venue_favorite_repository:
    path: packages/venue_fav_repo

  bloc: ^8.1.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  cupertino_icons: ^1.0.6
  firebase_database: ^10.4.5
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.5
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  rxdart: ^0.27.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
