name: glare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0 
  firebase_core: ^2.25.4
  firebase_database: ^10.4.5
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
