// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcGuEUvDbjJU-FIzOD0NFsrJ2_IeGpuw',
    appId: '1:718317121487:web:80996f2fe28750eef62cba',
    messagingSenderId: '718317121487',
    projectId: 'glare-8e959',
    authDomain: 'glare-8e959.firebaseapp.com',
    storageBucket: 'glare-8e959.appspot.com',
    measurementId: 'G-WWCCS16EEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7xGUAU3huprdes6UUSOztCUSHmWVwtsg',
    appId: '1:718317121487:android:c27f57890f752221f62cba',
    messagingSenderId: '718317121487',
    projectId: 'glare-8e959',
    storageBucket: 'glare-8e959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCng4zh29EoMLaO1kvFuutcUXdyCsnKFMU',
    appId: '1:718317121487:ios:f9ba2d8f161fc315f62cba',
    messagingSenderId: '718317121487',
    projectId: 'glare-8e959',
    storageBucket: 'glare-8e959.appspot.com',
    iosBundleId: 'com.example.glare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCng4zh29EoMLaO1kvFuutcUXdyCsnKFMU',
    appId: '1:718317121487:ios:e64405a774f95a1af62cba',
    messagingSenderId: '718317121487',
    projectId: 'glare-8e959',
    storageBucket: 'glare-8e959.appspot.com',
    iosBundleId: 'com.example.glare.RunnerTests',
  );
}
